[tool.poetry]
name = "maas"
version = "0.1.0"
description = ""
authors = ["Christtia Zheng <zchristtia@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
